DROP TABLE IF EXISTS Customers;
CREATE TABLE IF NOT EXISTS Customers (
    customer_id VARCHAR(16),
    customer_first_name VARCHAR(64),
    customer_last_name VARCHAR(64),
    name VARCHAR(64),
    customer_email VARCHAR(255),
    customer_note VARCHAR(255),
    ship_to VARCHAR(255),
    ship_street VARCHAR(255),
    ship_unit VARCHAR(64),
    ship_city VARCHAR(64),
    ship_state VARCHAR(16),
    ship_zip_code VARCHAR(10),
    ship_country VARCHAR(16),
    location VARCHAR(32),
    country VARCHAR(16),
    total_revenue INT,
    mrr DECIMAL(8,2),
    wrr DECIMAL(8,2),
    num_orders INT,
    num_subscriptions INT,
    subscription_status VARCHAR(32),
    payment_provider VARCHAR(32),
    last4 INT,
    source VARCHAR(255),
    marketplace_source BOOL,
    customer_metadata VARCHAR(255),
    ship_phone_number VARCHAR(10),
    PRIMARY KEY (customer_id)
);
