DROP TABLE IF EXISTS Subscriptions;
CREATE TABLE IF NOT EXISTS Subscriptions (
    shipment_id VARCHAR(16) NOT NULL,
    customer_id VARCHAR(10) NOT NULL,
    customer_name VARCHAR(64) NOT NULL,
    customer_email VARCHAR(64) NOT NULL,
    ship_to VARCHAR(64) NOT NULL,
    ship_company VARCHAR(512),
--  customer_first VARCHAR(32) NOT NULL,
--  customer_last VARCHAR(32) NOT NULL,
    ship_street VARCHAR(32) NOT NULL,
    ship_unit VARCHAR(16),
    ship_city VARCHAR(16) NOT NULL,
    ship_phone_number VARCHAR(10) NOT NULL,
    ship_state VARCHAR(2) NOT NULL,
    ship_zip_code VARCHAR(10) NOT NULL,
    ship_country VARCHAR(2) NOT NULL,
--  subscription_date DATETIME NOT NULL,
--  subscription_expire_original DATETIME NOT NULL,
    subscription_expire DATETIME NOT NULL,
    verification_status VARCHAR(64),
    verification_message VARCHAR(64),
    shipment_status VARCHAR(64),
    first_shipment VARCHAR(64),
    shipment_number INT,
    order_id VARCHAR(64),
    order_date DATETIME,
    target_ship_date DATETIME,
    subscription_cycle_count INT,
    customer_cycle_count INT,
    customer_notes VARCHAR(256),
    subscription_notes VARCHAR(256),
    subscription_term VARCHAR(64),
    tracking_number VARCHAR(64),
    subscription_metadata VARCHAR(256),
    cart_metadata VARCHAR(256),
    is_gift BOOL,
    gift_message VARCHAR(256),
    subscription_id VARCHAR(64),
    will_renew BOOL,
    gift_recipient_name VARCHAR(64),
    gift_recipient_email VARCHAR(64),
    shipped_at_date DATETIME,
    product_0_id VARCHAR(32),
    product_0_instance_id VARCHAR(32),
    product_0_name VARCHAR(18),
    product_0_sku VARCHAR(14),
    product_1_id VARCHAR(32),
    product_1_instance_id VARCHAR(32),
    product_1_name VARCHAR(18),
    product_1_sku VARCHAR(14),
    product_0_One_Time_Order VARCHAR(16),
    product_1_Flavor VARCHAR(32),
    product_0_FLAVOR_2 VARCHAR(32),
    product_0_FLAVOR_1 VARCHAR(32)
);
